name: CI Pipeline - Build Test

on:
  pull_request:
    branches: [main]

jobs:
  data_validation_and_test:
    runs-on: ubuntu-latest
    steps:
    # Get GitHub codes 
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4

    # Setup environment 
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

    # Setup packages
      - name: Setup Python packages
        run: pip install -r requirements.txt

      - name: Downloading Dataset and Overview
        run: python src/prepare_data.py --validate-only

      - name: Splitting data into Train/Test sets
        run: python src/prepare_data.py --split-check

      - name: Testing ML model built
        run: python src/train_model.py --dry-run

      - name: Checking metrics 
        run: python src/evaluate_model.py --ci-check

      # Save test report as an artifact
      - name: Installing test report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-report
          path: reports/ci-report.txt


        
    
    

      